services:
  www:
    build:
      context: .
      dockerfile: docker-php/Dockerfile
    container_name: ecoride_2025_www
    env_file:
      - ./.env.local
    ports:
      - 8000:80
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
      - /var/www/html/.git
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
    networks:
      - ecoride_2025
    command: >
      bash -c "chown -R www-data:www-data /var/www/html
      && chmod -R 755 /var/www/html
      && apache2-foreground"

  mysql:
    image: mysql
    platform: linux/x86_64
    container_name: ecoride_2025_mysql
    volumes:
      - ./var/db_data:/var/lib/mysql
    env_file:
      - ./.env.local
    ports:
      - 3307:3306
    networks:
      - ecoride_2025

  phpmyadmin:
    image: phpmyadmin
    container_name: ecoride_2025_phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - ecoride_2025
    environment:
      PMA_HOST: mysql

  mongo:
    image: mongo:6.0
    container_name: ecoride_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
volumes:
  mysql_data:
  mongo_data:
networks:
  ecoride_2025:
